# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
variables:
  - group: zappyhire-vars

stages:
- stage: DockerBuilAndPush
  jobs:
   - job: DockerBuilAndPush
     steps:
     #- task: Docker@2
     #  inputs:
     #   containerRegistry: 'sammas-docker-regiestry'
     #   repository: 'workshop'
     #   command: 'buildAndPush'
     #   Dockerfile: '**/Dockerfile'
     #   tags: 'zappyhire-$(Build.BuildId)'
     - task: CmdLine@2
       inputs:
         script: |
             docker build -t myapp .
             docker login -u $(docker_user) -p $(docker_pass)
             docker tag myapp $(docker_user)/workshop:zappyhire-$(Build.BuildId)
             docker push $(docker_user)/workshop:zappyhire-$(Build.BuildId)
        
  
