# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
variables:
  - group: zappyhire-vars

stages:
- stage: DockerBuilAndPush
  jobs:
   - job: DockerBuilAndPush
     steps:
     - task: CmdLine@2
       inputs:
         script: |
             docker build -t myapp .
             docker login -u $(docker_user) -p $(docker_pass)
             docker tag myapp $(docker_user)/workshop:zappyhire-$(Build.BuildId)
             docker push $(docker_user)/workshop:zappyhire-$(Build.BuildId)
- stage: TerraformDeploy
  jobs:
   - job: TerraformDeploy
     steps:
     - task: TerraformInstaller@0
       displayName: Terraform_install
       inputs:
         terraformVersion: 'latest' 
     - task: Bash@3
       displayName: Terraform_init
       inputs:
         targetType: 'inline'
         script: |
           cd cdn/
           terraform init
     - task: Bash@3
       displayName: Terraform_Apply
       inputs:
         targetType: 'inline'
         script: |
           cd cdn/
           terraform apply -var client_id=$(client_id) -var client_secret=$(client_secret) -var tenant_id=$(tenant_id) -var subscription_id=$(subscription_id) -var docker_user=$(docker_user) -var docker_pass=$(docker_pass) -var image_tag=zappyhire-$(Build.BuildId) -auto-approve

        
  
